### ISSUE TITLE
extract specific video segments at given time intervals

### ISSUE THREAD

**Issue by garyvalue** [avibn/telegram-downloader#5]
When forwarding videos to bots, extract specific video segments at given time intervals
/clip https://t.me/xxx/55547 00:00:00-00:01-12
00:00:00-00:01:12 is the time interval
Or define the time interval in the title, or other implementation methods
Are you considering this aspect of functionality?

**Comment by avibn** [comment]
Hi @garyvalue, thanks for suggesting the feature. Unfortunately, I don't think it's something that we need at the moment. The bot was mainly just made for downloading large video files sent as a whole - I'm not sure when this feature would be necessary. I will try add a few feature issues in the coming days, so there is a clear direction of any future works on this project :)
Thanks
